package com.shl.springboot.projectTemplate.domain.mapper;

import com.shl.springboot.projectTemplate.domain.entity.TestProjectTemplate;
import com.shl.springboot.projectTemplate.domain.entity.TestProjectTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestProjectTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    long countByExample(TestProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int deleteByExample(TestProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int insert(TestProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int insertSelective(TestProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    List<TestProjectTemplate> selectByExample(TestProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    TestProjectTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestProjectTemplate record, @Param("example") TestProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int updateByExample(@Param("record") TestProjectTemplate record, @Param("example") TestProjectTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int updateByPrimaryKeySelective(TestProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated Sun Dec 29 16:53:00 CST 2019
     */
    int updateByPrimaryKey(TestProjectTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TestProjectTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TestProjectTemplate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TestProjectTemplate> list, @Param("selective") TestProjectTemplate.Column ... selective);
}